apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    # These labels are how Kyverno policies target this namespace
    platform.io/managed: "true"
    platform.io/cluster: {{ .Values.clusterName }}
    platform.io/environment: {{ .Values.environment }}
    platform.io/cloud: {{ .Values.cloud }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    platform.io/managed: "true"
    platform.io/component: observability
