# GCP dev spoke — override only what differs from _template defaults
clusterName: gcp-dev
environment: dev
cloud: gcp
region: us-central1

# GCP specific
gcpProjectID: "shoshone-devops-platform" 

cilium:
  enabled: false
  k8sServiceHost: "136.114.8.131"

# Dev cluster — smaller footprint
prometheus:
  prometheus:
    prometheusSpec:
      replicas: 1
      retention: 1h
      retentionSize: "4GB"

kyverno:
  admissionController:
    replicas: 1