apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-dev
  namespace: capi-dev
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.243.0.0/16
    services:
      cidrBlocks:
        - 10.95.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtCluster
    name: capi-dev
    namespace: capi-dev
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: capi-dev-controlplane
    namespace: capi-dev
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: capi-dev
  namespace: capi-dev
spec:
  controlPlaneServiceTemplate:
    spec:
      type: LoadBalancer
